---
- hosts: hypervisor
  become: true

  vars:
    user: root
    home: "/root"
    undercloud_ip: 192.168.122.253
    netmask: 255.255.255.0
    gateway: 192.168.122.1
    dns: 192.168.122.1

  tasks:

    - name: Create stack user to be used from underclound
      user:
        name: stack
        comment: "Undercloud stack user"

    - name: Create stack user identity key for remote access
      command:
        ssh-keygen -b 2048 -t rsa -f {{ home }}/.ssh/stack-id_rsa -q -N ""
      args:
        creates: "{{ home }}/.ssh/stack-id_rsa"

    - name: Read pubkey for stack user
      command: >
        cat "{{ home }}/.ssh/stack-id_rsa.pub"
      register: stack_pubkey
      changed_when: false

    - name: Allow pubkey access to stack user
      authorized_key:
        user: stack
        state: present
        key: "{{ stack_pubkey.stdout }}"

    - name: Allow stack user to user libvirt
      copy:
        src: hypervisor/etc/polkit-1/localauthority/50-local.d/50-libvirt-user-stack.pkla
        dest: /etc/polkit-1/localauthority/50-local.d/50-libvirt-user-stack.pkla

    - name: Check undercloud VM status
      command: >
        virsh domstate undercloud
      register: undercloud_status
      ignore_errors: true
      changed_when: false

    - when: undercloud_status|failed
      block:

        - name: Create undercloud image
          command:
            qemu-img create -f qcow2 -b /var/lib/libvirt/images/rhel7-guest.qcow2 /tmp/undercloud.qcow2

        - name: Customize underclow image
          shell: |
            virt-customize \
              -a /tmp/undercloud.qcow2 \
              --hostname undercloud \
              --root-password password:redhat \
              --uninstall cloud-init \
              --copy-in '{{ home }}/.ssh:{{ home }}' \
              --run-command 'chcon system_u:object_r:ssh_home_t:s0 {{ home }}/.ssh {{ home }}/.ssh/authorized_keys' \
              --run-command 'sed -i s/ONBOOT=.*/ONBOOT=no/g /etc/sysconfig/network-scripts/ifcfg-eth0' \
              --run-command 'cat << EOF > /etc/sysconfig/network-scripts/ifcfg-eth1
            DEVICE=eth1
            ONBOOT=yes
            IPADDR={{ undercloud_ip }}
            NETMASK={{ netmask }}
            GATEWAY={{ gateway }}
            NM_CONTROLLED=no
            DNS1={{ dns }}
            EOF'

        - name: Install underclow image
          command: >
            mv /tmp/undercloud.qcow2 /var/lib/libvirt/images/undercloud.qcow2

        - name: Remove undercloud from knwo_hosts file
          shell: |
            grep -v -e '^undercloud,' '{{ home }}/.ssh/known_hosts' > /tmp/known_hosts
            mv /tmp/known_hosts '{{ home }}/.ssh/known_hosts'

        - name: Create undercloud VM
          command: >
            virt-install \
              --ram 8192 \
              --vcpus 1 \
              --os-variant rhel7 \
              --disk path=/var/lib/libvirt/images/undercloud.qcow2,device=disk,bus=virtio,format=qcow2 \
              --import --noautoconsole --vnc \
              --network network:provisioning \
              --network network:default \
              --name undercloud

        - name: Autostart undercloud when restarting hypervisor
          command:
            virsh autostart undercloud

    - name: Start undercloud VM
      when: undercloud_status|succeeded and undercloud_status.stdout != "running"
      command:
        virsh start undercloud
