---
- hosts: hypervisor
  become: true

  vars:
    image_dir: /var/lib/libvirt/images
    hypervisor_ip: 192.168.122.1
    nodes:
      - name: ctrl01
        ram: 16384
        vcpus: 2
        disks: [ctrl01]
        vbmc_port: 6230

      - name: ctrl02
        ram: 16384
        vcpus: 2
        disks: [ctrl02]
        vbmc_port: 6231

      - name: ctrl03
        ram: 16384
        vcpus: 2
        disks: [ctrl03]
        vbmc_port: 6232

      - name: compute01
        ram: 4096
        vcpus: 4
        disks: [compute01]
        vbmc_port: 6233

      - name: compute02
        ram: 4096
        vcpus: 4
        disks: [compute02]
        vbmc_port: 6234

      - name: ceph01
        ram: 4096
        vcpus: 2
        disks: [ceph01, ceph01-storage]
        vbmc_port: 6235

      - name: ceph02
        ram: 4096
        vcpus: 2
        disks: [ceph02, ceph02-storage]
        vbmc_port: 6236

      - name: ceph03
        ram: 4096
        vcpus: 2
        disks: [ceph03, ceph03-storage]
        vbmc_port: 6237

      - name: networker
        ram: 4096
        vcpus: 2
        disks: [networker]
        vbmc_port: 6238


  tasks:

    - name: List overcloud VMs
      shell: |
        virsh list --all | awk '
          ($2 ~ /^overcloud-/){
            sub(/^overcloud-/, "", $2)
            print $2
          }'

      changed_when: false
      register: list_undercloud_vms

    - name: Define VMs
      with_items: "{{ nodes }}"
      when: item.name not in list_undercloud_vms.stdout_lines
      shell: >
        {% for disk in item.disks %}
        qemu-img create \
          -f qcow2 \
          -o preallocation=metadata \
          {{ image_dir }}/overcloud-{{ disk }}.qcow2 \
          60G
        {% endfor %}
        virt-install \
          --ram {{ item.ram }} \
          --vcpus {{ item.vcpus }} \
          --os-variant rhel7 \
          {% for disk in item.disks %} \
          --disk path={{ image_dir }}/overcloud-{{ disk }}.qcow2,device=disk,bus=virtio,format=qcow2 \
          {% endfor %} \
          --noautoconsole \
          --vnc \
          --network network:provisioning \
          --network network:default \
          --network network:default \
          --name overcloud-{{ item.name }} \
          --cpu host \
          --dry-run --print-xml > /tmp/overcloud-{{ item.name }}.xml && \
        virsh define --file /tmp/overcloud-{{ item.name }}.xml

    - name: Install Virtual BMC
      yum:
        name:
          - python-virtualbmc
          - ipmitool
        state: installed

    - name: Create systemd unit file for Virtual BMC service
      copy:
        src: hypervisor/usr/lib/systemd/system/virtualbmc@.service
        dest: /usr/lib/systemd/system/virtualbmc@.service

    - name: List Virtual BMC nodes
      shell: |
        vbmc list | awk '
          ($2 ~ /^overcloud-/){
            sub(/^overcloud-/, "", $2)
            print $2
          }'

      changed_when: false
      register: list_vbmc_vms

    - name: Add VMs to Virtual BMC
      with_items: "{{ nodes }}"
      when: item.name not in list_vbmc_vms.stdout_lines
      command: >
        vbmc add overcloud-{{ item.name }}
          --port {{ item.vbmc_port }}
          --username admin
          --password redhat

    - name: Enable and start virtualbmc@overcloud services
      with_items: "{{ nodes }}"
      systemd:
        name: "virtualbmc@overcloud-{{ item.name }}"
        enabled: true
        state: started

    - name: Open firewall ports for Virtual BMC from undercloud
      with_items: "{{ nodes }}"
      firewalld:
        source: "{{ hypervisor_ip }}"
        port: "{{ item.vbmc_port }}/udp"
        state: enabled
        permanent: true
      register: open_vbmc_ports

    - name: Restart firewalld
      when: open_vbmc_ports|changed
      service:
        name: firewalld
        enabled: yes
        state: restarted
