---

- hosts: undercloud
  become: true
  gather_facts: no

  vars:
    hypervisor_ip: 192.168.122.1
    home: /root

  tasks:

    - name: Wait for system to become reachable
      wait_for_connection:
        timeout: 60

    - name: Gather facts for first time
      setup:

    - name: Set hostname
      hostname:
        name: undercloud
      register: set_hostname

    - name: Restart network manager service
      when: set_hostname|changed
      systemd:
        name: network
        enabled: yes
        state: restarted

    - name: Configure /etc/hosts file
      copy:
        src: undercloud/etc/hosts
        dest: /etc/hosts

    - name: Get ipervisor packages access RPM
      get_url:
        url: "http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm"
        dest: /tmp/rhos-release-latest.noarch.rpm

    - name: Enable ipervisor packages access
      yum:
        name: /tmp/rhos-release-latest.noarch.rpm
        state: present

    - name: Enable the latest OSP director and RHEL packages
      shell: >
        rhos-release 11-director
      changed_when: false

    - name: Upgrade all packages
      yum:
        name: "*"
        state: latest

    - name: Get last kernel
      shell: |
        rpm -q --last kernel |
        awk '
          {
            sub(/kernel-/,"")
            print $1
            exit 0
          }'
      changed_when: false
      register: last_kernel

    - name: Check current kernel
      command: >
        uname -r
      register: current_kernel
      changed_when: false

    - when: last_kernel.stdout != current_kernel.stdout
      block:

        - name: Reboot {{ inventory_hostname }} node
          shell: >
            sleep 2 && reboot "Reboot required to update kernel."
          ignore_errors: true
          async: 1
          poll: 0

        - name: Wait for system to become reachable
          wait_for_connection:
            delay: 5
            timeout: 300

        - name: Check current kernel
          command: >
            uname -r
          register: current_kernel
          changed_when: false
          failed_when: last_kernel.stdout != current_kernel.stdout


    - name: Install libvirt packages
      yum:
        state: installed
        name:
          - libvirt
          - libguestfs-tools

    - name: Install TripleO client
      yum:
        state: installed
        name:
          - python-tripleoclient

    - name: Create stack user to be used from underclound
      user:
        name: stack
        comment: "Undercloud stack user"
        state: present
        createhome: yes

    - name: Allow passwordless sudo to stack user
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^stack ALL='
        line: 'stack ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

    - name: Read pubkey for stack user
      command: >
        cat "{{ home }}/.ssh/id_rsa.pub"
      register: stack_pubkey
      changed_when: false

    - name: Allow pubkey access to stack user
      authorized_key:
        user: stack
        state: present
        key: "{{ stack_pubkey.stdout }}"

    - name: Copy ssh keys files
      copy:
        src: "{{ home }}/.ssh/{{ item }}"
        dest: "/home/stack/.ssh"
        remote_src: yes
        owner: stack
        group: stack
        mode: 0600

      with_items:
        - id_rsa
        - id_rsa.pub

    - name: Configure SSH client connections
      copy:
        src: common/ssh/config
        dest: "/home/stack/.ssh/config"
        owner: stack
        group: stack
        mode: 0600

    - name: Install IPMI tool
      yum:
        state: installed
        name:
          - ipmitool
