- hosts: undercloud
  become: true
  become_user: stack

  vars:
    home: /home/stack

  tasks:

    - name: Get overcloud images
      shell: |
        source "{{ home }}/stackrc"
        openstack image list -f yaml

      register: overcloud_images_yaml
      changed_when: false

    - name: Parse overcloud images
      set_fact:
        overcloud_images: >
          {{ overcloud_images_yaml.stdout|from_yaml }}

    - name: Get overcloud image names
      set_fact:
        overcloud_image_names: >
          {{
            overcloud_images|
            map(attribute='Name')|
            list
          }}

    - when: ('bm-deploy-kernel' not in overcloud_image_names) or
            ('bm-deploy-ramdisk' not in overcloud_image_names) or
            ('overcloud-full' not in overcloud_image_names) or
            ('overcloud-full-initrd' not in overcloud_image_names) or
            ('overcloud-full-vmlinuz' not in overcloud_image_names)
      block:

        - debug:
            var: overcloud_image_names
            verbosity: 2

        - name: Install the OSP 11 image package
          become_user: root
          yum:
            name: rhosp-director-images
            state: installed

        - name: Create directory for images
          file:
            path: "{{ home }}/images"
            state: directory
          register: create_images_dir

        - name: Extract images
          command:
            tar -xvf /usr/share/rhosp-director-images/ironic-python-agent.tar '{{ item }}'
          args:
            chdir: "{{ home }}/images"
            creates: "{{ home }}/images/{{ item }}"
            warn: false
          with_items:
            - ironic-python-agent.initramfs
            - ironic-python-agent.kernel

        - name: Extract OSP 11 images
          command:
            tar -xvf /usr/share/rhosp-director-images/overcloud-full-latest-11.0.tar '{{ item }}'
          args:
            chdir: "{{ home }}/images"
            creates: "{{ home }}/images/{{ item }}"
            warn: false
          with_items:
            - overcloud-full.qcow2
            - overcloud-full.initrd
            - overcloud-full.vmlinuz

        - name: Set root password for full image
          shell: |
            virt-customize \
              -a ~/images/overcloud-full.qcow2 \
              --root-password password:redhat

        - name: Customize overcloud full image
          shell: |
            virt-customize \
              -a ~/images/overcloud-full.qcow2 \
              --run-command '
                rpm -ivh http://rhos-release.virt.bos.redhat.com/repos/rhos-release/rhos-release-latest.noarch.rpm &&
                rhos-release 11 -r 7.4'

        - name: Upload overcloud images
          shell: |
            source "{{ home }}/stackrc"
            openstack overcloud image upload --image-path '{{ home }}/images/'

        - name: Get overcloud images
          shell: |
            source "{{ home }}/stackrc"
            openstack image list -f yaml

          register: overcloud_images_yaml
          changed_when: false

        - name: Parse overcloud images
          set_fact:
            overcloud_images: >
              {{ overcloud_images_yaml.stdout|from_yaml }}

        - name: Parse overcloud image names
          set_fact:
            overcloud_image_names: >
              {{
                overcloud_images|
                map(attribute='Name')|
                list
              }}
          failed_when:
            ('bm-deploy-kernel' not in overcloud_image_names) or
            ('bm-deploy-ramdisk' not in overcloud_image_names) or
            ('overcloud-full' not in overcloud_image_names) or
            ('overcloud-full-initrd' not in overcloud_image_names) or
            ('overcloud-full-vmlinuz' not in overcloud_image_names)

    - debug:
        var: overcloud_image_names
        verbosity: 2
