---
- hosts: undercloud
  become: true
  become_user: stack

  vars:
    home: /home/stack

    ntp_servers:
      - 10.35.255.6
      - 10.35.28.1

  tasks:

    - name: Install TripleO heat templates
      become_user: root
      yum:
        name: openstack-tripleo-heat-templates-compat
        state: installed

    - name: Get node profiles
      shell: |
        source '{{ home }}/stackrc'
        openstack overcloud profiles list -f yaml
      changed_when: false
      register: profile_nodes_yaml

    - name: Get node UIID by flavors
      set_fact: 
        profile_nodes: '{{ profile_nodes_yaml.stdout|from_yaml }}'

    - name: Get node UIID by flavors
      set_fact:
        '{{ item.var }}': >
          {{
            profile_nodes|
            selectattr('Current Profile', 'equalto', '{{ item.flavor }}')|
            list
          }}
      with_items:
        - var: control_nodes
          flavor: control
        - var: compute_nodes
          flavor: compute

    - name: Deploy overcloud
      shell: |
        source '{{ home }}/stackrc'
        openstack overcloud deploy \
          --templates /usr/share/openstack-tripleo-heat-templates/newton/ \
          {% for ntp_server in ntp_servers %}
            --ntp-server '{{ ntp_server }}' \
          {% endfor %}
          --control-scale 1 \
          --control-flavor control \
          --compute-scale 1 \
          --compute-flavor compute
