---
- hosts: undercloud
  become: true
  become_user: stack

  vars:
    home: /home/stack
    subnet_name: ctlplane-subnet
    dns_nameservers: 192.168.122.1

  tasks:

    - name: Create templates directories
      file:
        path: '{{ item.dest }}'
        state: directory
      with_items:
        - src: /usr/share/openstack-tripleo-heat-templates/newton
          dest: '{{ home }}/templates'
        - src: /usr/share/openstack-tripleo-heat-templates/network/config/bond-with-vlans
          dest: '{{ home }}/templates/nic-configs'
      register: create_template_directory

    - name: Copy template directories
      shell: |
        cp -r {{ item.src }}/* '{{ item.dest }}'
      with_items: >
        {{
          create_template_directory.results|
          selectattr('changed')|
          map(attribute='item')|
          list
        }}

    - name: Create network environment template
      copy:
        src: undercloud/templates/network-environment.yaml
        dest: '{{ home }}/templates/network-environment.yaml'
