---
- hosts: undercloud
  become: true
  become_user: stack

  vars:
    home: /home/stack

    ntp_servers:
      - 10.35.255.6
      - 10.35.28.1

    control_scale: 3
    compute_scale: 2

    ssh_identity_file: "{{ lookup('env', 'SSH_IDENTITY_FILE') }}"

  tasks:

    - fail:

    - name: Get node profiles
      shell: |
        source '{{ home }}/stackrc'
        openstack overcloud profiles list -f yaml
      changed_when: false
      register: profile_nodes_yaml

    - name: Get node UIID by flavors
      set_fact: 
        profile_nodes: '{{ profile_nodes_yaml.stdout|from_yaml }}'

    - name: Select nodes UIID by flavors
      set_fact:
        '{{ item.var }}': >
          {{
            profile_nodes|
            selectattr('Current Profile', 'equalto', item.flavor)|
            selectattr('Provision State', 'equalto', 'active')|
            list
          }}
      with_items:
        - var: active_control_nodes
          flavor: control
        - var: active_compute_nodes
          flavor: compute

    - when: ((active_control_nodes|length) != control_scale) or
            ((active_compute_nodes|length) != compute_scale)
      block:

        - name: Install TripleO heat templates
          become_user: root
          yum:
            name: openstack-tripleo-heat-templates-compat
            state: installed

        - name: Deploy overcloud
          shell: |
            source '{{ home }}/stackrc'
            openstack overcloud deploy \
              --templates /usr/share/openstack-tripleo-heat-templates/newton/ \
              {% for ntp_server in ntp_servers %}
                --ntp-server '{{ ntp_server }}' \
              {% endfor %}
              --control-scale '{{ control_scale }}' \
              --control-flavor control \
              --compute-scale '{{ compute_scale }}' \
              --compute-flavor compute

    - name: Get overcloud nodes network detais
      shell: |
        source '{{ home }}/stackrc'
        openstack server list -f yaml
      changed_when: false
      register: overcloud_nodes_network_detais_yaml

    - name: Parse overcloud nodes network detais
      set_fact:
        overcloud_nodes_network_detais: >
          {{ overcloud_nodes_network_detais_yaml.stdout|from_yaml }}

    - name: Select active overcloud nodes by flavour
      set_fact:
        '{{ item.var }}': >
          {{
            overcloud_nodes_network_detais|
            selectattr('Status', 'equalto', 'ACTIVE')|
            selectattr('Name', 'search', item.match_name)|
            list
          }}
      with_items:
        - var: control_nodes_network_detais
          match_name: '^overcloud-controller-'
        - var: compute_nodes_network_detais
          match_name: '^overcloud-compute-'

    - name: Check active overcloud nodes counts
      when: >
        (item.nodes|length) != item.scale
      fail:
        msg: >
          Actual active nodes: {{ item.nodes|length }}.
          Expected {{ item.scale }}.
      with_items:
        - nodes: '{{ control_nodes_network_detais }}'
          scale: '{{ control_scale }}'
        - nodes: '{{ compute_nodes_network_detais }}'
          scale: '{{ compute_scale }}'

    - name: "Populate hosts file"
      become_user: root
      lineinfile:
        path: /etc/hosts
        regexp: '.* {{ item.Name }}$'
        state: present
        line: >
          {{
            item.Networks.split(', ')|
            select('search', '^ctlplane=')|
            first|
            replace('ctlplane=', '', count=1)
          }} {{ item.Name }}
      with_items: >
        {{ overcloud_nodes_network_detais }}

    - name: Copy identity files
      copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      with_items:
        - src: '{{ ssh_identity_file }}'
          dest: /tmp/pub_key
        - src: '{{ ssh_identity_file }}.pub'
          dest: /tmp/pub_key.pub

    - name: Copy authentication keys to overcloud nodes
      shell: |
        ssh-copy-id \
          -i /tmp/pub_key \
          -o PasswordAuthentication=no \
          -o StrictHostKeyChecking=no \
          'heat-admin@{{ item.Name }}'
      with_items: >
        {{ overcloud_nodes_network_detais }}

    - name: Copy overcloudrc file to overcloud control nodes
      shell:
        scp \
          -oStrictHostKeyChecking=no \
          ~/overcloudrc \
          "heat-admin@{{ item.Name }}:/home/heat-admin"
      with_items: >
        {{ control_nodes_network_detais }}
