---
- hosts: overcloud
  become: true
  become_user: heat-admin

  vars:
    home: /home/heat-admin

  tasks:

    - name: List overcloud images
      shell: |
        source ~/overcloudrc
        openstack image list -f yaml
      register: overcloud_images_yaml
      changed_when: false

    - name: Parse overcloud images
      set_fact:
        overcloud_images: >
          {{ overcloud_images_yaml.stdout|from_yaml }}

    - when: >
        (
          overcloud_images|
          selectattr('Name', 'equalto', 'cirros')|
          list|
          length
        ) == 0
      block:

        - name: Download Cirros image
          get_url:
            url: http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
            dest: /tmp

        - name: Upload the image to overcloud
          shell: |
            source ~/overcloudrc
            openstack image create cirros \
              --file /tmp/cirros-0.3.5-x86_64-disk.img \
              --disk-format qcow2 \
              --container-format bare \
              --public

        - name: List overcloud images
          shell: |
            source ~/overcloudrc
            openstack image list -f yaml
          register: overcloud_images_yaml
          changed_when: false

        - name: Parse overcloud images
          set_fact:
            overcloud_images: >
              {{ overcloud_images_yaml.stdout|from_yaml}}

    - name: Select cirros image
      set_fact:
        cirros_image: >
          {{
            overcloud_images|
            selectattr('Name', 'equalto', 'cirros')|
            first
          }}

    - debug:
        var: cirros_image
        verbosity: 2


    - name: Get overcloud flavors
      shell: |
        source ~/overcloudrc
        openstack flavor list -f yaml
      register: overcloud_flavors_yaml
      changed_when: false

    - name: Parse overcloud falvors
      set_fact:
        overcloud_falvors: >
          {{ overcloud_flavors_yaml.stdout|from_yaml }}

    - when: >
        (
          overcloud_falvors|
          selectattr('Name', 'equalto', 'm1.tiny')|
          list|
          length
        ) == 0
      block:

        - name: Create flavor
          shell: |
            source ~/overcloudrc
            openstack flavor create --ram 512 --disk 2 --vcpus 1 --id auto m1.tiny

        - name: Get overcloud flavors
          shell: |
            source ~/overcloudrc
            openstack flavor list -f yaml
          register: overcloud_flavors_yaml
          changed_when: false

        - name: Parse overcloud falvors
          set_fact:
            overcloud_falvors: >
              {{ overcloud_flavors_yaml.stdout|from_yaml }}

    - name: Select flavor
      set_fact:
        flavour: >
          {{
            overcloud_falvors|
            selectattr('Name', 'equalto', 'm1.tiny')|
            first
          }}

    - debug:
        var: flavour
        verbosity: 2

