---
- hosts: target
  become: true

  vars:
    user: stack
    home: "/home/{{ user }}"

  tasks:

    - name: Check there is a big enought cloud image
      shell: >
        qemu-img info /var/lib/libvirt/images/rhel7-guest.qcow2 |
          grep -e '^virtual size: 40G'
      ignore_errors: true
      register: has_cloud_image

    - when: has_cloud_image|failed
      block:

        - name: Create a new image
          command: >
            qemu-img create -f qcow2 /tmp/rhel7-guest.qcow2 40G

        - name: Download RHEL 7.4 cloud image
          get_url:
            url: "http://10.12.50.1/pub/rhel-server-7.4-x86_64-kvm.qcow2"
            dest: /tmp/rhel7-guest-official.qcow2

        - name: Expand original image to the new one with a bigger size
          command: >
            virt-resize --expand /dev/sda1 \
                /tmp/rhel7-guest-official.qcow2 \
                /tmp/rhel7-guest.qcow2

        - name: Install newly generated image
          command: >
            mv /tmp/rhel7-guest.qcow2 /var/lib/libvirt/images/rhel7-guest.qcow2
