---
- hosts: target
  become: true

  vars:
    user: stack
    home: "/home/{{ user }}"
    ip_addr: 192.168.122.253
    netmask: 255.255.255.0
    gateway: 192.168.122.1
    dns: 192.168.122.1

  tasks:

    - name: Check undercloud VM status
      command: >
        virsh domstate undercloud
      ignore_errors: true
      register: undercloud_status

    - when: undercloud_status|failed
      block:

        - name: Create undercloud image
          command:
            qemu-img create -f qcow2 -b /var/lib/libvirt/images/rhel7-guest.qcow2 /tmp/undercloud.qcow2

        - name: Customize underclow image
          shell: |
            virt-customize \
              -a /tmp/undercloud.qcow2 \
              --root-password password:redhat \
              --uninstall cloud-init \
              --run-command 'sed -i s/ONBOOT=.*/ONBOOT=no/g /etc/sysconfig/network-scripts/ifcfg-eth0' \
              --run-command 'cat << EOF > /etc/sysconfig/network-scripts/ifcfg-eth1
            DEVICE=eth1
            ONBOOT=yes
            IPADDR={{ ip_addr }}
            NETMASK={{ netmask }}
            GATEWAY={{ gateway }}
            NM_CONTROLLED=no
            DNS1={{ dns }}
            EOF' \
              --firstboot-command 'hostnamectl set-hostname --static undercloud'

        - name: Install underclow image
          command: >
            mv /tmp/undercloud.qcow2 /var/lib/libvirt/images/undercloud.qcow2

        - name: Remove undercloud from knwo_hosts file
          shell: |
            grep -v -e '^undercloud,' /root/.ssh/known_hosts > /tmp/known_hosts
            mv /tmp/known_hosts /root/.ssh/known_hosts

        - name: Create undercloud VM
          command: >
            virt-install \
              --ram 8192 \
              --vcpus 1 \
              --os-variant rhel7 \
              --disk path=/var/lib/libvirt/images/undercloud.qcow2,device=disk,bus=virtio,format=qcow2 \
              --import --noautoconsole --vnc \
              --network network:provisioning \
              --network network:default \
              --name undercloud

    - name: Start undercloud VM
      when: undercloud_status|succeeded and undercloud_status.stdout != "running"
      command:
        virsh --connect qemu:///system start undercloud

    - name: Write undercloud ip to /etc/hosts
      shell: |
        awk '
          {
            for(i = 1; i <= NF; i++){
              if ($i == "undercloud")
                next;
            };
            print $0
          }

          END {
            print "{{ ip_addr }}" " undercloud"
          }
          ' /etc/hosts > /tmp/hosts
        mv /tmp/hosts /etc/hosts
